app:
  instance:
    code: portal
    profile: dev
  rest:
    # profile: dev
    profiles:
      datacenter: dev
  file:
    upload-path: d:\file\upload
    template-path: classpath:template
    images-root-path: d:/images
  authority:
    login:
      allow-retry-times: 3   # 登录失败超过该次数要求输入验证码
    menu:
      operate: false # 是否控制菜单按钮权限
  layout:
    menu:
      expand-first: true # 展开第一个菜单
  mq:
    enable: false # 暂停使用
    exchange: bv.data
    routes:
      data: bv.datacenter.data
    queues:
      data: bv.data.portal
  task:
    exchange: "0 0/60 * * * ?"
  redis:
    prefix: PORTAL
    # 过期时间，以秒为单位
    # expire: 3600
  error:
    prefix: P
  token:
    access:
      # 超时时间，以秒为单位
      expire: 600
    refresh:
      expire: 1200
  ess:
    host: 127.0.0.1
    port: 8113
server:
  port: 7003
  session:
    timeout: 300
logging:
  level:
    root: info
    com.bestvike: debug
    org.springframework.security: warn
  # 默认日志文件名
  # file: log
  # 默认日志路径
  # path: ./log
  # logback.xml路径，默认为classpath:logback.xml
  # config: ./logback.xml
security:
  sessions: always
# redis:
  # single:
  #   host: 127.0.0.1
  #   port: 6379
  # cluster:
  #   address: 127.0.0.1:20001,127.0.0.1:20002,127.0.0.1:20003
  #   timeout: 300000
  #   maxRedirections: 6
  # pool:
    # maxWaitMillis: -1
    # maxTotal: 1000
    # maxIdle: 9
    # minIdle: 100
spring:
  application:
    name: ${app.instance.code}-${app.instance.profile}
#  session:
#    store-type: none
  redis:
    # cluster:
    #   nodes: 127.0.0.1:20001,127.0.0.1:20002,127.0.0.1:20003
    host: 127.0.0.1
    port: 6379
  http:
    multipart.max-file-size: 100Mb
    encoding:
      force: true
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  resources:
    cache-period: 3600000
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: admin
    password: admin
    virtual-host: /
    publisher-confirms: true
datasources:
  portal:
    datasource:
      url: jdbc:oracle:thin:@172.10.10.68:1521/bvbdc # jdbc:oracle:thin:@172.16.9.2:1521/orcl
      username: zjb
      password: zjb
      driverClassName: oracle.jdbc.OracleDriver # org.mariadb.jdbc.Driver #
      # 初始化大小，最小，最大
      initialSize: 6
      minIdle: 4
      maxIdle: 15
      maxActive: 22
      # 配置获取连接等待超时的时间
      maxWait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      minEvictableIdleTimeMillis: 300000
      validationQuery: select 1 from dual
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
    mybatis:
      dialect: org.apache.ibatis.dialect.OracleDialect # org.apache.ibatis.dialect.MariadbDialect
      basePackage: com.bestvike.commons.extend.dao.ds1,com.bestvike.commons.dao,com.bestvike.portal.dao,com.bestvike.bvch.dao #com.bestvike.commons.dao
      aliasesPackage: com.bestvike.commons.data,com.bestvike.portal.data,com.bestvike.bvch.data
      mapperLocations: classpath*:com/bestvike/commons/mapping/AbstractMapper.xml,classpath*:com/bestvike/commons/extend/mapping/AbstractMapper1.xml,classpath*:com/bestvike/portal/mapping/*.xml,classpath*:com/bestvike/bvch/mapping/*.xml #com/bestvike/commons/mapping/*.xml
      underscoreToCamelCase: true
  frame:
    datasource:
      url: jdbc:oracle:thin:@172.10.10.68:1521/bvbdc # jdbc:oracle:thin:@172.16.9.2:1521/orcl
      username: bvdf_frame_dzpy  # bvframe
      password: bvdf_frame_dzpy  # bvframe
      driverClassName: oracle.jdbc.OracleDriver # org.mariadb.jdbc.Driver #
      # 初始化大小，最小，最大
      initialSize: 6
      minIdle: 4
      maxIdle: 15
      maxActive: 22
      # 配置获取连接等待超时的时间
      maxWait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      minEvictableIdleTimeMillis: 300000
      validationQuery: select 1 from dual
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
    mybatis:
      dialect: org.apache.ibatis.dialect.OracleDialect # org.apache.ibatis.dialect.MariadbDialect
      basePackage: com.bestvike.commons.extend.dao.ds2,com.bestvike.frame.dao
      aliasesPackage: com.bestvike.frame.data
      mapperLocations: com/bestvike/commons/mapping/AbstractMapper.xml,classpath*:com/bestvike/commons/extend/mapping/AbstractMapper2.xml,classpath*:com/bestvike/frame/mapping/*.xml
      underscoreToCamelCase: true
  rfis:
    datasource:
      url: jdbc:oracle:thin:@172.10.10.68:1521/bvbdc # jdbc:oracle:thin:@172.16.9.2:1521/orcl
      username: bvdf_dzpy  # bvrfis
      password: bvdf_dzpy  # bvrfis
      driverClassName: oracle.jdbc.OracleDriver # org.mariadb.jdbc.Driver #
      # 初始化大小，最小，最大
      initialSize: 6
      minIdle: 4
      maxIdle: 15
      maxActive: 22
      # 配置获取连接等待超时的时间
      maxWait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      minEvictableIdleTimeMillis: 300000
      validationQuery: select 1 from dual
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
    mybatis:
      dialect: org.apache.ibatis.dialect.OracleDialect # org.apache.ibatis.dialect.MariadbDialect
      basePackage: com.bestvike.commons.extend.dao.ds3,com.bestvike.rfis.dao
      aliasesPackage: com.bestvike.rfis.data
      mapperLocations: classpath*:com/bestvike/commons/mapping/AbstractMapper.xml,classpath*:com/bestvike/commons/extend/mapping/AbstractMapper3.xml,classpath*:com/bestvike/rfis/mapping/*.xml
      underscoreToCamelCase: false
  ess:
    datasource:
      url: jdbc:oracle:thin:@127.0.0.1:1521/bvbdc # jdbc:mariadb://127.0.0.1:3306/bvportal
      username: bvdf_dzpy
      password: bvdf_dzpy
      driverClassName: oracle.jdbc.OracleDriver # org.mariadb.jdbc.Driver
      # 初始化大小，最小，最大
      initialSize: 6
      minIdle: 4
      maxIdle: 15
      maxActive: 22
      # 配置获取连接等待超时的时间
      maxWait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      minEvictableIdleTimeMillis: 300000
      validationQuery: select 1 from dual
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
    mybatis:

      dialect: org.apache.ibatis.dialect.OracleDialect # org.apache.ibatis.dialect.MariadbDialect
      basePackage: com.bestvike.commons.extend.dao.ds4,com.bestvike.ess.dao
      aliasesPackage: com.bestvike.ess.data
      mapperLocations: classpath*:com/bestvike/commons/mapping/AbstractMapper.xml,classpath*:com/bestvike/commons/extend/mapping/AbstractMapper4.xml,classpath*:com/bestvike/ess/mapping/*.xml
      underscoreToCamelCase: true

config:
  #平原行政区化代码
  XZQHDM: 371426
  #理论业务类别
  LLYWLB: 商品期房转让网签
  #交易业务证明证书名称
  JYYWZMZSMC: 商品期房转让合同备案证
  #普通交易者类别
  JYZLB: 受让方
  #普通交易者类别编码
  JYZLBBM: "05"
  #企业交易者类别
  QYJYZLB: 出让人
  #企业交易者类别编码
  QYJYZLBBM: "01"
  #导入表的开始编号                           平原县开始序号1260000001   陵城区开始序号1030000001
  KSXH: 126
  #接口密码
  portpassword: dzpy
